### PR TITLE
fix deprecations and modernize development dependencies

### PR DESCRIPTION
**Pull request by mtoygar**
with ember 3.6 merge polyfill and router.on('didTransition', () => {}) usage is deprecated.

ref:
https://deprecations.emberjs.com/v3.x/#toc_deprecate-router-events
https://deprecations.emberjs.com/v3.x/#toc_ember-polyfills-deprecate-merge

ember-cli-google-tag-manager was subject to these deprecations. I resolved the router deprecation in the first commit. Later I upgraded addon's development dependencies to ember 3.10. these upgrade both resolved the ember-cli-babel deprecation and merge polyfill deprecation.

I tested locally on my project using `yarn link` and do not encounter with a problem. Also, I update the `ember-try.js`. test wont fail on ember 2.18, 3.4, ember-canary and ember-default.

### CODE REVIEW

**Comment by mtoygar** [comment]
@Soulou can you find a chance to look this pr?

**Comment by mtoygar** [comment]
@Soulou any opinions? we can publish as a major version change also, I believe this modernization would help lots of users of `ember-cli-google-tag-manager`

**Comment by mtoygar** [comment]
First, I am so sorry to disturb you all by tagging. I tagged you since you were under Scalingo organization. This pr is stale since June and I hope that you can direct me to a maintainer or share your comments/review regarding this pr.

We are running this fork on production since June 17 and does not encounter with any problems so far. How can we proceed, can you help?

cc: @yannski @Soulou @johnsudaar @EtienneM @brandon-welsch

**Comment by Soulou** [comment]
Thanks a lot for the delay @mtoygar 

Actually we haven't been really active because we're not using actively Ember.js right now.

Would you be interested by getting the lead on this package?

**Comment by mtoygar** [comment]
I would be delighted, @Soulou. Your project is already steady and to the point. It shouldn't require lots of spare time and I think I can handle this responsibility.

**Comment by Soulou** [comment]
Great, I'm going to merge this and proceed to a transfer, should it go to an Organization or to you personally?

**Comment by mtoygar** [comment]
We can transfer directly to me, @Soulou

**Comment by Soulou** [comment]
@mtoygar I can't transfer it because you've already a fork, if you don't have other PR to open, can you delete your fork?

**Comment by mtoygar** [comment]
@Soulou I have deleted my fork.

**Comment by Soulou** [comment]
Request sent, then we'll have to do the same with NPM

**Comment by Soulou** [comment]
@mtoygar Can you give me your NPM user?

**Comment by mtoygar** [comment]
@Soulou it is mtoygar. 
https://www.npmjs.com/~mtoygar

**Comment by Soulou** [comment]
https://www.npmjs.com/~mtoygar done

**Comment by mtoygar** [comment]
I will bump it to `1.0.0` soon and I will inform you when it is done. Thanks for all your help @Soulou

**Comment by mtoygar** [comment]
@Soulou done 👌

**Pull request merged**
